name: Ermete CachyOS Addons (Encapsulated)

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-cachyos-addons.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  FEDORA_VERSION: 43

jobs:
  build-cachyos-addons:
    name: 📦 Encapsulate CachyOS Addons
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    container:
      image: registry.fedoraproject.org/fedora:43
      options: --privileged
    steps:
      - name: Fetch RPMs from COPR
        run: |
          mkdir -p /github/home/RPMS
          curl -Lo /etc/yum.repos.d/bieszczaders-kernel-cachyos-addons.repo "https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos-addons/repo/fedora-${FEDORA_VERSION}/bieszczaders-kernel-cachyos-addons-fedora-${FEDORA_VERSION}.repo"
          sed -i "s/%{fedora}/${FEDORA_VERSION}/g" /etc/yum.repos.d/bieszczaders-kernel-cachyos-addons.repo
          dnf download --resolve --alldeps --destdir=/github/home/RPMS bore-sysctl scx-scheds scx-tools

      - name: Publish Micro-Container OCI
        run: |
          dnf install -y buildah
          export STORAGE_DRIVER=vfs
          export BUILDAH_ISOLATION=chroot
          buildah login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}
          ctr=$(buildah from scratch)
          buildah copy $ctr /github/home/RPMS/*.rpm /
          IMAGE_LOWER=$(echo "${{ env.REGISTRY }}/${{ github.repository_owner }}/ermete-forge-cachyos-addons:latest" | tr '[:upper:]' '[:lower:]')
          buildah commit $ctr $IMAGE_LOWER
          buildah push $IMAGE_LOWER
